
import javax.swing.DefaultListModel;
import javax.swing.JFrame;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CMS6227
 */
public class PartsPanel extends javax.swing.JPanel {

    /**
     * Creates new form PartsPanel
     */
    
    private Manager manager;
    private NewJFrame parentFrame;
    
    public PartsPanel(NewJFrame parentFrame) {
        initComponents();
        this.setSize(742, 710);
        this.setVisible(true);
        this.parentFrame = parentFrame;
        DefaultListModel listModel = new DefaultListModel();
        PartRenderer pr = new PartRenderer();
        jList1.setCellRenderer(pr);
        
        Part p = new Rim(100, "rsc/daytona_rim.png");
        Part q = new Rim(150, "rsc/smootie_rim.png");
        listModel.addElement(p);
        listModel.addElement(q);
//        for (Part p: parentFrame.manager.rimsList.allParts) {
//            listModel.addElement(p);
//            System.out.println(p);
//        }
        jList1.setModel(listModel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
