
import javax.swing.DefaultListModel;
import javax.swing.JFrame;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CMS6227
 */
public class PartsPanel extends javax.swing.JPanel {

    /**
     * Creates new form PartsPanel
     */
    
    private Manager manager;
    private NewJFrame parentFrame;
    
    public PartsPanel(NewJFrame parentFrame) {    
        initComponents();
        this.setSize(742, 710);
        this.setVisible(true);
        this.parentFrame = parentFrame;
        this.manager = Manager.getInstance();
        manager.partsPanel = this;
        updateRemainingBudget();
        DefaultListModel listModel = new DefaultListModel();
        PartRenderer pr = new PartRenderer();
        rimGUIList.setCellRenderer(pr);
        
        for (Part p: Manager.getInstance().rimsList.visibleParts) {
            listModel.addElement(p);
        }
        rimGUIList.setModel(listModel);
        rimGUIList.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        rimGUIList = new javax.swing.JList();
        addRimButton = new javax.swing.JButton();
        remainingBudgetLabel = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setMaximumSize(new java.awt.Dimension(742, 710));
        setMinimumSize(new java.awt.Dimension(742, 710));
        setPreferredSize(new java.awt.Dimension(742, 710));

        rimGUIList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rimGUIListMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(rimGUIList);

        addRimButton.setText("Add Rim");
        addRimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRimButtonActionPerformed(evt);
            }
        });

        remainingBudgetLabel.setText("jLabel1");

        jCheckBox1.setText("jCheckBox1");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addRimButton)
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 403, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(remainingBudgetLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(remainingBudgetLabel)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addRimButton)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox1)))
                .addContainerGap(531, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addRimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRimButtonActionPerformed
        // remove list contents
//        for (Part p: Manager.getInstance().rimsList.visibleParts) {
//            listModel.addElement(p);
//        }
        rimGUIList.setVisible(true);

    }//GEN-LAST:event_addRimButtonActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        Manager.getInstance().budget.addObserver(Manager.getInstance().rimsList);
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void rimGUIListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rimGUIListMousePressed
        Part selectedPart = (Part) rimGUIList.getSelectedValue();
        manager.currentVehicle.addPart(selectedPart);
        System.out.println(selectedPart);
        updateRemainingBudget();
    }//GEN-LAST:event_rimGUIListMousePressed

    private void updateRemainingBudget(){
        manager.budget.calculateRemainingBudget(manager.currentVehicle);
        remainingBudgetLabel.setText("Remaining Budget: " + Double.toString(Budget.getRemainingBudget()));
    }
    
    public void updateLists() {
        DefaultListModel listModel = new DefaultListModel();
        for (Part p: Manager.getInstance().rimsList.visibleParts) {
            listModel.addElement(p);
        }
        rimGUIList.setModel(listModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRimButton;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel remainingBudgetLabel;
    private javax.swing.JList rimGUIList;
    // End of variables declaration//GEN-END:variables
}
